[colors.primary]
background = '#1e1e2e'
foreground = '#cdd6f4'

[colors.selection]
text = '#cdd6f4'
background = '#24586a'

[colors.cursor]
text = '#1e1e2e'
cursor = '#89dceb'

[colors.normal]
black   = '#181825'
red     = '#ff72a2'
green   = '#75eb80'
yellow  = '#fff572'
blue    = '#6fcedf'
magenta = '#19606c'
cyan    = '#89dceb'
white   = '#e7f4f6'

[colors.bright]
black   = '#8d9798'
red     = '#ff9fc0'
green   = '#a5ffae'
yellow  = '#fff8a5'
blue    = '#a4f1ff'
magenta = '#b4f3ff'
cyan    = '#cff7ff'
white   = '#f8feff'
